services:
  - type: web
    name: jeunesse-eglise
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn jeunesse_eglise.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
